### ISSUE TITLE
why run the checkBinaryCache once?

### ISSUE THREAD

**Issue by loganfreeman** [SassDoc/sass-convert#15]
It only runs one time, but didn't notice the user that it has been used. No information is bad.

```js
/**
 * Run binary checks only once.
 *
 * @return {Promise}
 */
function checkBinaryCache() {
  if (!('promise' in checkBinaryCache)) {
    checkBinaryCache.promise = checkBinary(BIN);
  }

  return checkBinaryCache.promise;
}
```

**Comment by pascalduez** [comment]
Hi,

this is not a forum or social chat.  
If you lack time or patience for writing detailed, constructive and polite issues, we can't help you.
