### ISSUE TITLE
 /usr/bin/ruby2.1: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by select** [SassDoc/sass-convert#16]
I installed sass-convert with 
```
sudo npm install -g sass-convert
```
and get the following error
```
$ sass-convert --help
bash: /usr/local/bin/sass-convert: /usr/bin/ruby2.1: bad interpreter: No such file or directory
```
changing `#!/usr/bin/ruby2.1` to `#!/usr/bin/ruby` in `/usr/local/bin/sass-convert` still returns an error

```
/usr/local/bin/sass-convert:23:in `load': cannot load such file -- /usr/share/rubygems-integration/all/gems/sass-3.4.21/bin/sass-convert (LoadError)
	from /usr/local/bin/sass-convert:23:in `<main>'
```

**Comment by select** [comment]
Ok I solved it with 
```
$ sudo gem install sass
```

**Comment by linkanp** [comment]
This works for me
1. Open Terminal
2. Install Homebrew:   ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
3. Do not close Terminal, open Mac Appstore and check Update, install all XCode Command Line Tools updates OR in my case, XCode Command Line Tools started install automaticly throught Terminal right after step 2.
4. Back to Terminal
5. Install Ruby:   brew install rbenv ruby-build
6. Install SASS gem:   sudo gem install -n /usr/local/bin sass

**Comment by YOUR1** [comment]
> I was also facing this issue after updating to MacOS Catalina. This works for me.
> 
>     1. Open Terminal
> 
>     2. Install Homebrew:         ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
> 
>     3. Do not close Terminal, open Mac Appstore and check Update, install all XCode Command Line Tools updates OR in my case, XCode Command Line Tools started install automaticly throught Terminal right after step 2.
> 
>     4. Back to Terminal
> 
>     5. Install Ruby:         brew install rbenv ruby-build
> 
>     6. Install SASS gem:         sudo gem install -n /usr/local/bin sass

Executed step 5 and 6 after upgrading to Catalina, and it's working again. Thanks for your contribution!
