### ISSUE TITLE
Unneeded blackslash added

### ISSUE THREAD

**Issue by prettydiff** [SassDoc/sass-convert#23]
Please see the details at https://github.com/Glavin001/atom-beautify/issues/2352

**Comment by pascalduez** [comment]
Hi,

`sass-convert` is not performing any processing in itself, it's just a binding to Ruby Sass `sass-convert` binary. So I would start looking there. 
Also they are both deprecated.

**Comment by prettydiff** [comment]
Ahh, thank you very much!
