### ISSUE TITLE
sass-convert is run even with no .sass file

### ISSUE THREAD

**Issue by HugoGiraudel** [SassDoc/sass-convert#6]
Deduced from: https://github.com/lunelson/sass-maps-plus/pull/12.

**Comment by valeriangalliat** [comment]
Can't reproduce on Linux. This might be a Mac specific bug.

**Comment by pascalduez** [comment]
Well, I can't reproduce on a OSX either...

If there is not `.sass` files, the `sass-convert` binary checks are not invoked. 
Tested on `sass-maps-plus` as well as own tests.
