### ISSUE TITLE
Add a `rename` option

### ISSUE THREAD

**Issue by pascalduez** [SassDoc/sass-convert#7]
Current version does not modify the file name nor extension after convertion.
This is due to the fact that SassDoc is using the file name and path to source link.

https://github.com/SassDoc/sassdoc/blob/develop/src/parser.js#L76-L77
https://github.com/SassDoc/sassdoc-theme-default/blob/develop/views/includes/annotations/preview.html.swig#L11

So in the case of a project composed of `.sass` files we still want to be able to link to the original source file.

Proposed solution:
Add a new `rename` option `default: true` that will change the file extension reflecting the conversion.
In SassDoc core we will simply set that option to `false`.

**Comment by valeriangalliat** [comment]
:+1:

**Comment by pascalduez** [comment]
Added in #8 but made it opt in, so no change needed in SassDoc core.
